# Generated by Django 5.1.6 on 2025-04-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_batalla'),
    ]

    operations = [
        migrations.AddField(
            model_name='batalla',
            name='imagen',
            field=models.ImageField(default='inicio\\static\\img\\LogoHalcones.png', upload_to='imagenes_batallas/'),
        ),
    ]
