# Generated by Django 5.1.6 on 2025-04-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_batalla_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('nombre_capitan', models.CharField(max_length=100)),
                ('integrantes', models.TextField()),
            ],
        ),
    ]
