# Generated by Django 5.1.6 on 2025-05-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='categoria',
            field=models.CharField(choices=[('seguidor_linea', 'Seguidor de línea'), ('mini_zumo_rc', 'Mini Zumo RC'), ('mini_zumo_auto', 'Mini Zumo Autónomo')], default='seguidor_linea', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipo',
            name='integrantes',
            field=models.TextField(help_text='Separados por comas'),
        ),
    ]
