# Generated by Django 5.1.6 on 2025-05-11 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_equipo_categoria_alter_equipo_integrantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batalla',
            name='id',
        ),
        migrations.RemoveField(
            model_name='batalla',
            name='nombre',
        ),
        migrations.AddField(
            model_name='batalla',
            name='categoria',
            field=models.CharField(choices=[('SL', 'Seguidor de línea'), ('MSRC', 'Mini Sumo RC'), ('MSA', 'Mini Sumo Autónomo')], default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batalla',
            name='equipo_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='batallas_como_equipo_1', to='inicio.equipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batalla',
            name='equipo_2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='batallas_como_equipo_2', to='inicio.equipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batalla',
            name='ganador',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='batallas_ganadas', to='inicio.equipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batalla',
            name='numero',
            field=models.AutoField(default=4, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batalla',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batalla',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='batalla',
            name='imagen',
            field=models.ImageField(default='inicio/static/img/LogoHalcones.png', upload_to='imagenes_batallas/'),
        ),
    ]
