# Generated by Django 5.1.6 on 2025-05-11 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_remove_batalla_id_remove_batalla_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batalla',
            old_name='fecha',
            new_name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='batalla',
            name='equipo_1',
        ),
        migrations.RemoveField(
            model_name='batalla',
            name='equipo_2',
        ),
        migrations.RemoveField(
            model_name='batalla',
            name='imagen',
        ),
        migrations.AddField(
            model_name='batalla',
            name='cerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batalla',
            name='equipos',
            field=models.ManyToManyField(related_name='batallas', to='inicio.equipo'),
        ),
        migrations.AddField(
            model_name='batalla',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batalla',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batallas_ganadas', to='inicio.equipo'),
        ),
        migrations.CreateModel(
            name='Ronda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_equipo_1', models.DecimalField(decimal_places=2, help_text='Tiempo en segundos', max_digits=5)),
                ('tiempo_equipo_2', models.DecimalField(decimal_places=2, help_text='Tiempo en segundos', max_digits=5)),
                ('anotaciones_equipo_1', models.TextField(blank=True, help_text='Notas sobre el desempeño del equipo 1', null=True)),
                ('anotaciones_equipo_2', models.TextField(blank=True, help_text='Notas sobre el desempeño del equipo 2', null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cerrada', models.BooleanField(default=False)),
                ('batalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas', to='inicio.batalla')),
                ('equipo_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas_equipo_1', to='inicio.equipo')),
                ('equipo_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas_equipo_2', to='inicio.equipo')),
            ],
        ),
    ]
