# Generated by Django 5.1.1 on 2025-05-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_customgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
