# Generated by Django 5.1.1 on 2025-05-29 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_delete_customgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='batalla',
            name='ronda',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batalla_unica', to='inicio.ronda'),
        ),
    ]
