# Generated by Django 5.1.1 on 2025-05-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_delete_datosensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ronda',
            name='anotaciones_equipo_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ronda',
            name='anotaciones_equipo_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
