# Generated by Django 5.1.1 on 2025-05-29 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0012_alter_ronda_anotaciones_equipo_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batalla',
            name='ronda',
        ),
        migrations.AlterField(
            model_name='ronda',
            name='batalla',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ronda', to='inicio.batalla'),
        ),
        migrations.AlterField(
            model_name='ronda',
            name='tiempo_equipo_1',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tiempo en segundos', max_digits=5),
        ),
        migrations.AlterField(
            model_name='ronda',
            name='tiempo_equipo_2',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tiempo en segundos', max_digits=5),
        ),
    ]
