# Generated by Django 5.1.1 on 2025-05-29 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0013_remove_batalla_ronda_alter_ronda_batalla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ronda',
            name='anotaciones_equipo_1',
        ),
        migrations.RemoveField(
            model_name='ronda',
            name='anotaciones_equipo_2',
        ),
        migrations.RemoveField(
            model_name='ronda',
            name='equipo_1',
        ),
        migrations.RemoveField(
            model_name='ronda',
            name='equipo_2',
        ),
        migrations.RemoveField(
            model_name='ronda',
            name='tiempo_equipo_1',
        ),
        migrations.RemoveField(
            model_name='ronda',
            name='tiempo_equipo_2',
        ),
        migrations.CreateModel(
            name='ParticipacionRonda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.DecimalField(decimal_places=2, default=0, help_text='Tiempo en segundos', max_digits=6)),
                ('anotaciones', models.TextField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.equipo')),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='inicio.ronda')),
            ],
            options={
                'unique_together': {('ronda', 'equipo')},
            },
        ),
    ]
