# Generated by Django 5.1.1 on 2025-06-01 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0014_remove_ronda_anotaciones_equipo_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoEnEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.equipo')),
                ('ronda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inicio.ronda')),
            ],
        ),
    ]
