# Generated by Django 5.1.6 on 2025-06-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0015_equipoenespera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('batalla', 'Batalla'), ('otro', 'Otro')], max_length=50)),
                ('url_registro', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
