# Generated by Django 5.1.6 on 2025-06-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0017_alter_evento_descripcion_alter_evento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('batalla', 'Batalla'), ('otro', 'Otro')], max_length=20),
        ),
    ]
