# Generated by Django 5.1.6 on 2025-06-13 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0018_alter_evento_descripcion_alter_evento_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
