# Generated by Django 5.1.6 on 2025-06-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0019_delete_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='batalla',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos_batalla/'),
        ),
        migrations.AddField(
            model_name='batalla',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='batallas/'),
        ),
        migrations.AddField(
            model_name='batalla',
            name='link_info',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batalla',
            name='lugar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
