# Generated by Django 5.1.6 on 2025-06-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0020_batalla_archivo_batalla_imagen_batalla_link_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoBatalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('lugar', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('categoria', models.CharField(choices=[('SL', 'Seguidor de línea'), ('MSRC', 'Mini Sumo RC'), ('MSA', 'Mini Sumo Autónomo')], max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos_batalla/')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos_eventos/')),
                ('link_info', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='batalla',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='batalla',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='batalla',
            name='link_info',
        ),
        migrations.RemoveField(
            model_name='batalla',
            name='lugar',
        ),
    ]
